export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const DISABLED_BUTTON = "DISABLED_BUTTON";
export const ENABLE_BUTTON = "ENABLE_BUTTON";
